---

- name: plugins | Get data
  ansible.builtin.set_fact:
    _plugin_data:
      "{{ bareos_fd_plugin_list | selectattr('name', 'equalto', item) | list }}"
  loop: "{{ bareos_fd_plugins }}"

- name: plugins | Print var
  ansible.builtin.debug:
    msg: "Plugin data: {{ _plugin_data }}"

- name: plugins | Install Bareos plugin packages
  ansible.builtin.package:
    name: "{{ item.packages }}"
    state: present
  loop: _plugin_data
