---

- name: plugins | Get Bareos plugin package names
  ansible.builtin.set_fact:
    _plugin_packages:
      "{{ bareos_fd_plugin_list | selectattr('name', 'match', item) | map(attribute='package_name') }}"
  loop: "{{ bareos_fd_plugins }}"

- name: plugins | Install Bareos plugin packages
  ansible.builtin.package:
    name: "{{ _plugin_packages }}"
    state: present
