---

- name: plugins_ldap | Create plugin_defaults file
  ansible.builtin.template:
    src: "templates/plugin_ldap_defaults.ini.j2"
    dest: "/etc/bareos/bareos-fd.d/plugin_ldap_defaults.ini"
    backup: true
    owner: root
    group: root
    mode: "0644"
