---
# Settin up Relax-and-Recover (ReaR) according to https://docs.bareos.org/Appendix/DisasterRecoveryUsingBareos.html#configuration
# This requires

- name: rear | Install packages
  ansible.builtin.package:
    name: "{{ bareos_fd_rear_packages }}"
    state: present

- name: rear | Place local.conf
  ansible.builtin.template:
    src: templates/rear_local.conf.j2
    dest: /etc/rear/local.conf
    owner: root
    group: root
    mode: "0644"
    backup: "{{ bareos_fd_backup_configurations }}"

- name: rear | Place update-rear-rescue.sh
  ansible.builtin.template:
    src: templates/rear_update-rear-rescue.sh.j2
    dest: /usr/local/sbin/update-rear-rescue.sh
    owner: root
    group: root
    mode: "0755"
    backup: false  # avoid filling /usr/local/sbin

- name: rear | Place bconsole
  ansible.builtin.template:
    src: templates/rear_bconsole.conf.j2
    dest: /etc/bareos/bconsole.conf
    owner: bareos
    group: bareos
    mode: "0640"  # contains console secret
    backup: "{{ bareos_fd_backup_configurations }}"
  loop: "{{ bareos_fd_directors }}"  # use same logic as with the directors config
  loop_control:
    label: "{{ item.name }}"
  run_once: true  # avoid issues in loop
  when:
    - bareos_fd_rear_console_name is defined
    - bareos_fd_rear_console_pass is defined
