---
# handlers file for bareos_fd

- name: Check configuration
  ansible.builtin.command: "/usr/sbin/bareos-fd --test-config"
  changed_when: false

- name: Restart bareos-filedaemon
  ansible.builtin.service:
    name: "{{ bareos_fd_service }}"
    state: restarted

# required for the PostgreSQL backup plugin
# only used when PostgreSQL is installed on the FD
- name: Reload postgresql
  ansible.builtin.service:
    name: postgresql.service
    state: reloaded
