---

dependency:
  name: galaxy
  options:
    role-file: molecule/postgresql/requirements.yml
    requirements-file: molecule/postgresql/requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: "bareosfd-${image:-fedora38}${TOX_ENVNAME}"
    image: "geerlingguy/docker-${image:-fedora38}-ansible:latest"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
    systemd: true
provisioner:
  name: ansible
verifier:
  name: ansible
