---

name: Ansible Molecule

on:
  push:
    tags_ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '3 2 2 * *'

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: ansible-lint
        uses: ansible/ansible-lint@main

  test:
    needs:
      - lint
    uses: adfinis/github-workflows-bareos/.github/workflows/molecule.yaml@v0.5.1
    with:
      systems: |
        {
          "config": [
            {
              "image": "debian",
              "tag": "latest"
            },
            {
              "image": "debian",
              "tag": "bullseye"
            },
            {
              "image": "enterpriselinux",
              "tag": "8"
            },
            {
              "image": "enterpriselinux",
              "tag": "latest"
            },
            {
              "image": "fedora",
              "tag": "40"
            },
            {
              "image": "fedora",
              "tag": "latest"
            },
            {
              "image": "ubuntu",
              "tag": "jammy"
            },
            {
              "image": "ubuntu",
              "tag": "latest"
            }
          ]
        }

  test_postgresql:
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "debian12"
          - image: "fedora40"
          - image: "ubuntu2204"
          - image: "ubuntu2404"
          - image: "rockylinux9"
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"

      - name: molecule postgresql plugin scenario
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_args: "--scenario-name postgresql"
        env:
          image: ${{ matrix.config.image }}
